spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/conexao_lemure?createDatabaseIfNotExist=true
    username: root
    password: 12345678

server:
  port: 8091
